# Generated by Django 3.2.8 on 2022-05-07 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alchool',
            field=models.CharField(choices=[('alchoolisallowed', 'I drink alcohol or I am not against alcohol consumption at home.'), ('alchoolisnotallowed', 'I do not drink alcohol and I do not want alcohol consumed in my home.')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('nicosia', 'nicosia'), ('famagusta', 'famagusta'), ('kyrenia', 'kyrenia'), ('omorfo', 'omorfo'), ('lefka', 'lefka')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cityofarival',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.CharField(choices=[('hashome', 'I have a house and I am looking for a roommate for my house.'), ('nohome', 'I do not have a house, I am looking for a house and roommate.')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.CharField(choices=[('petsareallowed', 'I have a pet or I am not against keeping pets at home.'), ('petsarenotallowed', "I don't have a pet and I don't want any pets in my house.")], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.CharField(choices=[('smokingisallowed', 'I smoke or I am not against smoking in the home.'), ('smokingisnotallowed', "I don't smoke and I don't want smoking in my home.")], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpeg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
